site_name: Scholaretl
nav:
  - Home: index.md
  - Examples: examples.md
  - Endpoints: endpoints.md
  - Application Setup: setup.md
  - Reference: reference.md

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant.progress
    - navigation.sections
    - navigation.path
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
