name: Documentation Building and Pushing

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Build the documentation
        run: |
          pip install mkdocs-material mkdocstrings[python]
          mkdocs build
          mkdocs gh-deploy --force
